# Generated by Django 3.2.18 on 2023-02-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='time_minutes',
        ),
    ]
